### ISSUE TITLE
impl Drop for Allocation

### ISSUE THREAD

**Issue by Gordon01** [pcwalton/offset-allocator#2]
Hi, thank you for the project.
It's inspiring for idiomatic Rust in meta-allocators space.

What do you think about `Allocation` to implement `Drop` and (probably) not to implement `Clone`?

**Comment by pcwalton** [comment]
I considered it, but I decided that this was best done with a higher-level library that wraps `Allocation`. `Allocation` is like `*u8`, which is Copy and Clone and doesn't implement Drop.
